server:
  port: 8080

spring:
  application:
    name: deal
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/main-changelog.xml
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

calculator:
  url: ${CALCULATOR_URL:http://localhost:8081}

logging:
  level:
    root: INFO
    com.creditbank.deal: DEBUG
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
  server:
    port: 8081

kafka:
  topics:
    finish-registration: finish-registration
    create-documents: create-documents
    send-documents: send-documents
    send-ses: send-ses
    credit-issued: credit-issued
    statement-denied: statement-denied


email:
  messages:
    FINISH_REGISTRATION: "Требуется завершение регистрации"
    CREATE_DOCUMENTS: "Документы сформированы"
    SEND_DOCUMENTS: "Документы отправлены на подпись"
    SEND_SES: "Код подтверждения отправлен. Ваш код - {code}"
    CREDIT_ISSUED: "Кредит успешно выдан"
    STATEMENT_DENIED: "В заявке отказано"