version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: deal-postgres
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    networks:
      - internal
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  calculator:
    build:
      context: ./Calculator
      dockerfile: Dockerfile
    container_name: calculator-service
    networks:
      - internal

  deal:
    build:
      context: ./Deal
      dockerfile: Dockerfile
    container_name: deal-service
    depends_on:
      postgres:
        condition: service_healthy
      calculator:
        condition: service_started
    ports: ["8080:8080", "8081:8081"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://deal-postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      CALCULATOR_URL: http://calculator-service:8080
    networks:
      - internal
      - external

networks:
  internal:
    driver: bridge
  external:
    driver: bridge

volumes:
  pgdata: