server:
  port: 8080

spring:
  application:
    name: dossier
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_SMTP_USERNAME}
    password: ${GMAIL_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: ${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: ${SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES}
        spring.json.type.mapping: >
          com.creditbank.deal.dto.dossier.EmailMessage:com.creditbank.dossier.dto.EmailMessage

logging:
  level:
    root: INFO
    com.creditbank.dossier: DEBUG